### ISSUE TITLE
Refactor AuthenticateAdminController and AuthenticateUserController

### ISSUE THREAD

**Issue by nickedwards109** [nickedwards109/little-shop#73]
Rename methods from authenticate_user and authenticate_admin to something like verify_admin_authentication etc, since these methods are not actually authenticating the user but are checking whether the user is authenticated. Also, I think the controller inheritance structure would be easier to understand if these controllers were placed in the controllers/admin directory and controllers/user directory, respectively (instead of in the controllers directory itself)

**Comment by rongxanh88** [comment]
Maybe this should be AuthorizedAdminController and AuthorizedUserController?
